name: Postman Workflow Collection Trigger

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: self-hosted-ubuntu-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          mkdir -p newman
          newman run "Inwarranty-flow Collection.postman_collection.json" \
            -e "QA.postman_environment.json" \
            -d "testData.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/*.html

      - name: Creating GitHub Pages branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Sending email notifications
        if: always()
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: abishekh01112000@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: Phoenix-Inwarranty-Flow-Collection-Run-Report
          body: |
            Hello,
            The Phoenix Inwarranty Flow Postman Collection execution has completed.
            Please find the attached link : https://abishekh-rajendhran.github.io/Phoenix-Inwarranty-Flow/

            Regards,
            GH Actions!
          
            
          
          
          
          
          
        
